### ISSUE TITLE
Community package requirements: sanity tests

### ISSUE THREAD

**Issue by gotmax23** [NetApp/santricity#23]
(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `1.4.0` of `netapp_eseries.santricity`, corresponding to the `v1.4.0` tag in this repo, fails one or more of the required sanity tests.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

**Issue truncated. [Click here to read more](https://gist.github.com/gotmax23/c5a3ace03c9f7f6a76f1980c7b234fcb).**

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

**Comment by gundalow** [comment]
@mcwhiteside @VuTran007 Can you fix these?

If you need help, please ask.
Otherwise this collection will be removed from the `ansible` community package

**Comment by VuTran007** [comment]
Thanks @gotmax23 and @gundalow, @mcwhiteside and I are looking into it.

**Comment by gotmax23** [comment]
Thanks for following up, @VuTran007. You can find the results for this collection tested against the latest version of ansible at https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/netapp_eseries.santricity.md.

**Comment by gotmax23** [comment]
@VuTran007, @mcwhiteside, any update here?

**Comment by VuTran007** [comment]
> @VuTran007, @mcwhiteside, any update here?

Apologies for the delay. We were diverted by other urgent tasks. We have resolved all failures in the Ansible tests, and the collection will now go through the standard security review process before we can publish the changes.

**Comment by gotmax23** [comment]
What's the status of the internal review process?

**Comment by VuTran007** [comment]
> What's the status of the internal review process?

The changes are going through the approval process. Expecting to have approval by next week.

**Comment by VuTran007** [comment]
This issue is resolved in `Release 1.4.1`. The changes passed on `ansible-test version 2.17.3`. Test result:

```
ansible-test sanity --python 3.12

Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
Running sanity test "changelog"
Running sanity test "compile" on Python 3.12
Running sanity test "empty-init"
Running sanity test "ignores"
Running sanity test "import" on Python 3.12
Running sanity test "line-endings"
Running sanity test "no-assert"
Running sanity test "no-get-exception"
Running sanity test "no-illegal-filenames"
Running sanity test "no-smart-quotes"
Running sanity test "pep8"
Running sanity test "pslint"
Running sanity test "pylint"
Running sanity test "replace-urlopen"
Running sanity test "runtime-metadata"
Running sanity test "shebang"
Running sanity test "shellcheck"
Running sanity test "symlinks"
Running sanity test "use-argspec-type-path"
Running sanity test "use-compat-six"
Running sanity test "validate-modules"
Running sanity test "yamllint"
```

**Comment by VuTran007** [comment]
@gotmax23 

Could you please inform us if we can proceed with closing this issue?

**Comment by gotmax23** [comment]
Thanks for fixing this!
