### ISSUE TITLE
Unmaintained collection: Removal from the Ansible Community Package

### ISSUE THREAD

**Issue by mariolenz** [NetApp/santricity#24]
It looks like this collection is effectively unmaintained. According to the current [Ansible Community Package Collections Removal Process](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_package_removal.html#unmaintained-collections), we will consider removing it in a future version of the Ansible Community Package. Please see [Unmaintained collection: netapp_eseries.santricity](https://forum.ansible.com/t/6574) for more information.

At least one month after this announcement appears here and on [Bullhorn](https://forum.ansible.com/c/news/bullhorn/17), the Ansible Community Steering Committee will vote on whether this collection is considered unmaintained and will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 12. Please note that people can still manually install the collection with `ansible-galaxy collection install netapp_eseries.santricity` even when it has been removed from the Ansible Community Package.

**Comment by gundalow** [comment]
@ndswartz Are you still involved with the NetApp collection?

**Comment by gundalow** [comment]
> @gundalow - @VuTran007 and I are currently involved with maintaining the NetApp collection.

Thanks folks
Can you please take a look at https://github.com/NetApp/santricity/issues/23 and get that resolved. If you need help please reply to that GitHub issue

**Comment by VuTran007** [comment]
> > @gundalow - @VuTran007 and I are currently involved with maintaining the NetApp collection.
> 
> Thanks folks Can you please take a look at #23 and get that resolved. If you need help please reply to that GitHub issue

Thanks @gundalow. We are looking into it.

**Comment by VuTran007** [comment]
@mariolenz and @gundalow 

Can we close this issue since `Release 1.4.1` resolved the issue in https://github.com/NetApp/santricity/issues/23?

**Comment by mariolenz** [comment]
Closing because I see there has been a new release.
